services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - "5672"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend:/app/
      - ./frontend/public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
      - postgres

  # Add more containers below (nginx, postgres, etc.)
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    env_file:
      - .env

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474  # HTTP port
      - 7687:7687  # Bolt port
    env_file:
      - .env
    volumes:
      - neo4j_data:/data


  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/code
    restart: always
    ports:
      - 3001:3001
      - 5678:5678
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=LightRAG
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    restart: always

volumes:
  postgresql_data:
  neo4j_data:
  milvus:
  etcd:
  minio:
  mongodb_data:

networks:
  milvus:
    external: true



